name: ayet_rehberi
description: Kuran Chat Assistant - Flutter mobile application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  
  # State Management
  provider: ^6.1.2
  
  # HTTP & API
  http: ^1.2.2
  dio: ^5.7.0
  
  # Storage
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  
  # Sharing & Image
  share_plus: ^10.0.2
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.1
  
  # Utils
  uuid: ^4.5.1
  intl: ^0.19.0
  purchases_flutter: ^9.10.1
  flutter_secure_storage: ^10.0.0
  purchases_ui_flutter: ^9.10.1
  
  # Audio
  just_audio: ^0.9.40
  audio_session: ^0.1.21
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/share_backgrounds/
    - assets/PaywallAnimation/
    - assets/achievements/
    - assets/UI/ICONS/
    - assets/UI/100.Ayet1x/
    - assets/GettyImages-606920431.jpg

  # Fonts
  fonts:
    - family: OggText
      fonts:
        - asset: assets/fonts/OggText-Light-Trial.otf
          weight: 300
        - asset: assets/fonts/OggText-LightItalic-Trial.otf
          weight: 300
          style: italic
        - asset: assets/fonts/OggText-Book-Trial.otf
          weight: 400
        - asset: assets/fonts/OggText-Italic-Trial.otf
          weight: 400
          style: italic
        - asset: assets/fonts/OggText-Medium-Trial.otf
          weight: 500
        - asset: assets/fonts/OggText-MediumItalic-Trial.otf
          weight: 500
          style: italic
        - asset: assets/fonts/OggText-Bold-Trial.otf
          weight: 700
        - asset: assets/fonts/OggText-BoldItalic-Trial.otf
          weight: 700
          style: italic
        - asset: assets/fonts/OggText-ExtraBold-Trial.otf
          weight: 800
        - asset: assets/fonts/OggText-ExtraBoldItalic-Trial.otf
          weight: 800
          style: italic
    - family: ChiswellMedian
      fonts:
        - asset: assets/fonts/ChiswellMedian-Italic.otf
          style: italic


